version: 3

tasks:
  build:
    cmds:
      - g++ -o aoc main.cpp utils/file.cpp days/day1.cpp days/day2.cpp 
        days/day3.cpp days/day4.cpp days/day5.cpp days/day6.cpp 
        days/day7.cpp -std=c++17
